In [4]:
import numpy as np
ar=np.array([10,20,30,40,50])
print(ar[0])

10


In [5]:
ar=np.array([[10,20,30],[40,50,8],[7,5,2]])
print(ar[1,2])

8


In [6]:
arr=np.array([10,15,20,25,30])
print(arr[arr>20])

[25 30]


In [7]:
arr=np.array([10,15,20,25,30])
print(arr[(arr>10)&(arr<30)])

[15 20 25]


In [8]:
arr=np.array([1,2,3,4,5])
print(arr[[0,2,4]])

[1 3 5]


In [9]:
arr=np.array([1,2,3,4,5])
indeces=[0,2,4]
print(arr[indeces])

[1 3 5]
